# Generated by Django 3.0 on 2020-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201228_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='signupform',
            table=None,
        ),
    ]
