# Generated by Django 3.0 on 2020-12-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201231_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlumniMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('FatherName', models.CharField(max_length=200)),
                ('Batch', models.IntegerField()),
                ('MobileNo', models.IntegerField()),
                ('Email', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('URN', models.IntegerField()),
                ('Branch', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('Workingstatus', models.CharField(max_length=200)),
            ],
        ),
    ]
