# Generated by Django 3.0 on 2020-12-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201231_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventalumnimeet',
            name='Batch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventalumnimeet',
            name='MobileNo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventalumnimeet',
            name='URN',
            field=models.CharField(max_length=500),
        ),
    ]
